apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "mbyra.testing@gmail.com"
  GMAIL_PASSWORD: "pbvpxvswfumehyrw" # enable and use application password
type: Opaque